platform :ios, '11.0'

target 'Air Quality' do
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'R.swift', '~> 4.0'
  pod 'PromiseKit', '~> 4.4'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'RxSwift', '~> 4.1'
  pod 'RxCocoa', '~> 4.1'
  pod 'RxDataSources', '~> 3.0'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
end

target 'Air QualityTests' do
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'R.swift', '~> 4.0'
  pod 'PromiseKit', '~> 4.4'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'RxSwift', '~> 4.1'
  pod 'RxCocoa', '~> 4.1'
  pod 'RxDataSources', '~> 3.0'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'OHHTTPStubs', '~> 6.1.0'
  pod 'OHHTTPStubs/Swift'
end
