platform :ios, '11.0'

target 'Air Quality' do
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'R.swift', '~> 4.0'
  pod 'PromiseKit', '~> 4.4'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'RxSwift', '~> 4.1'
  pod 'RxCocoa', '~> 4.1'
  pod 'RxDataSources', '~> 3.0'
  pod 'SwiftyJSON'

  target 'Air QualityTests' do
    inherit! :search_paths
  end
end
